# Global options
NUM_EPISODES = 1500
GAMMA = 0.9999
NORMALIZE_STRATEGY = "NONE" # "MINMAX" OR "STANDARD" OR "NONE"

# Actor parameters
ACTOR_SIZE = 4
ACTOR_LR = 3e-3
ACTOR_DROPOUT_RATE = 0.00
ACTOR_L2_ALPHA = 0
ACTOR_TWO_NN_LAYERS = False
ACTOR_SCHEDULER_PATIENCE = 200
ACTOR_SCHEDULER_MIN_LR = 3e-4
ACTOR_SCHEDULER_FACTOR = 0.32

# Critic parameters
CRITIC_SIZE = 4
CRITIC_LR = 6e-3
CRITIC_DROPOUT_RATE = 0.00
CRITIC_L2_ALPHA = 0
CRITIC_TWO_NN_LAYERS = False
CRITIC_SCHEDULER_PATIENCE = 200
CRITIC_SCHEDULER_MIN_LR = 6e-4
CRITIC_SCHEDULER_FACTOR = 0.32