# Global options
NUM_EPISODES = 1000
GAMMA = 0.9999
NORMALIZE_STRATEGY = "NONE" # "MINMAX" OR "STANDARD" OR "NONE"

# Actor parameters
ACTOR_SIZE = 4
ACTOR_LR = 2e-3
ACTOR_DROPOUT_RATE = 0.00
ACTOR_L2_ALPHA = 0
ACTOR_TWO_NN_LAYERS = False

# Critic parameters
CRITIC_SIZE = 4
CRITIC_LR = 5e-3
CRITIC_DROPOUT_RATE = 0.00
CRITIC_L2_ALPHA = 0
CRITIC_TWO_NN_LAYERS = False