# Global options
NUM_EPISODES = 5000
GAMMA = 0.999
NORMALIZE_STRATEGY = "STANDARD" # "MINMAX" OR "STANDARD" OR "NONE"

# Actor parameters
ACTOR_SIZE = 32
ACTOR_LR = 8e-4
ACTOR_DROPOUT_RATE = 0.03
ACTOR_L2_ALPHA = 1e-5
ACTOR_SCHEDULER_PATIENCE = 2000
ACTOR_SCHEDULER_MIN_LR = 8e-4
ACTOR_SCHEDULER_FACTOR = 0.5
ACTOR_ENTROPY_BETA = 0

# Critic parameters
CRITIC_SIZE = 32
CRITIC_LR = 8e-4
CRITIC_DROPOUT_RATE = 0.03
CRITIC_L2_ALPHA = 1e-5
CRITIC_SCHEDULER_PATIENCE = 2000
CRITIC_SCHEDULER_MIN_LR = 8e-4
CRITIC_SCHEDULER_FACTOR = 0.5