# Global options
NUM_EPISODES = 3000
GAMMA = 0.999
NORMALIZE_STRATEGY = "STANDARD" # "MINMAX" OR "STANDARD" OR "NONE"

# Actor parameters
ACTOR_SIZE = 128
ACTOR_LR = 5e-4
ACTOR_DROPOUT_RATE = 0.00
ACTOR_L2_ALPHA = 0
ACTOR_SCHEDULER_PATIENCE = 300
ACTOR_SCHEDULER_MIN_LR = 1e-5
ACTOR_SCHEDULER_FACTOR = 0.5
ACTOR_ENTROPY_BETA = 0.001

# Critic parameters
CRITIC_SIZE = 128
CRITIC_LR = 5e-4
CRITIC_DROPOUT_RATE = 0.00
CRITIC_L2_ALPHA = 0
CRITIC_SCHEDULER_PATIENCE = 300
CRITIC_SCHEDULER_MIN_LR = 1e-5
CRITIC_SCHEDULER_FACTOR = 0.5